### ISSUE TITLE
installing directory

### ISSUE THREAD

**Issue by yehudarav** [KaplanOpenSource/Hermes#11]
After installing with 
./install -o ~/Programs/Hermes 

I get the following directory structure: 

-Programs
              - Hermes 
                         - docker.sh and the rest. 
                         - build 
                         - dot_local 
                         - examples 
                         - Hermes 
                                      - doc 
                                      - freecad 
                                      - hermes 

Is it possible to remove one hierarchy? 
-Programs
              - Hermes 
                         - docker.sh and the rest. 
                         - build 
                         - dot_local 
                         - examples 
                         - doc 
                         - freecad 
                         - hermes

**Comment by jackitg** [comment]
Hi, 
I have a bit different listing here, not exactly what you asked, 1 litter diff:
> ls -1 install_playground_linux_newStruct
Hermes
build
docker.sh
docker_dev.sh
docker_dev_compile.sh
dot_local
examples
source

Hermes is the repository dir, other stuff are products of the installation script. Could it be that  "hermes" in your directory is a leftover ?

**Comment by yehudarav** [comment]
No, inside Hermes there is the hermes directory with the python code. 
so the Hermes you see is redundant.

**Comment by jackitg** [comment]
I am against moving the Hermes/* to the root of the installation dir,  it will produce considerable clutter.

**Comment by yehudarav** [comment]
The structure now is way too complicated. 
Hermes/Hermes/hermes is way too much. 

I suggest that after install -o [DIR]/Hermesflow

- Hermesflow/Hermes --> Hermesflow/[some other name that represent its functionality. 
                                                            why is it different than source?]

- Hermesflow/Hermes/herms --> Hermesflow/herms

btw, why do we need the build/hermes
