### ISSUE TITLE
Fails to install 

### ISSUE THREAD

**Issue by OfirBlumer** [KaplanOpenSource/Hermes#18]
Hi jack, 

we are tying to install on a station and get the following error: 
`Checking connectivity... done.
Checking out files: 100% (10286/10286), done.
Checking out files: 100% (5249/5249), done.
HEAD is now at 5a352ea FEM: solver fenics, fix fenics import test
Hash  0.18-1194-g5a352ea63 wasn't cheked out`

However, on a different computer there wasn't any problem. 
Any ides?

**Comment by jackitg** [comment]
Hi Ofir, can you please produce a debug output by adding -v argument? it fails checking out freecad, I would like to have the detailed output. After producing the debug out: can you  rename   the source directory inside the destination and retry ?

Thanks.

**Comment by OfirBlumer** [comment]
+ getopts o:b:d:f:p:i:vh opt
++ uname -s
+ OS=Linux
+ DESTINATION_FULL=
+ DOCKER_DEV=
+ DOCKER=
++ get_abs_filename ''
++++ dirname ''
+++ cd .
+++ pwd
+++ basename ''
++ echo /home/ofir/Downloads/Hermes/
+ DESTINATION_FULL=/home/ofir/Downloads/Hermes/
+ FREECAD_SOURCE_PATCH=/home/ofir/Downloads/Hermes//Hermes_git/freecad_5a352ea63_git.diff
+ mkdir -p /home/ofir/Downloads/Hermes/
+ cd /home/ofir/Downloads/Hermes/
+ DOCKER=/home/ofir/Downloads/Hermes//docker.sh
+ DOCKER_DEV=/home/ofir/Downloads/Hermes//docker_dev.sh
+ DOCKER_DEV_COMPILE=/home/ofir/Downloads/Hermes//docker_dev_compile.sh
+ git_pull HermesFlow/Hermes Hermes_git
+ res=0
+ branchopts=
+ '[' xmaster '!=' xmaster ']'
++ git clone https://github.com/HermesFlow/Hermes.git Hermes_git
+ git_clone_output='Cloning into '\''Hermes_git'\''...'
+ echo 'Cloning into '\''Hermes_git'\''...'
Cloning into 'Hermes_git'...
+ [[ xCloning into 'Hermes_git'... = x*fatal:* ]]
+ [[ xCloning into 'Hermes_git'... = x*fatal:* ]]
+ [[ xCloning into 'Hermes_git'... = xfatal:* ]]
+ [[ xCloning into 'Hermes_git'... = *error:* ]]
+ return 0
+ check_docker
++ which docker
+ docker=/usr/bin/docker
+ '[' -z /usr/bin/docker ']'
+ return 0
+ setup_docker
+ docker_inspect_cmd='docker image inspect -f "{{.Id}}" registry.gitlab.com/daviddaish/freecad_docker_env'
++ docker image inspect -f '"{{.Id}}"' registry.gitlab.com/daviddaish/freecad_docker_env
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.40/images/registry.gitlab.com/daviddaish/freecad_docker_env/json: dial unix /var/run/docker.sock: connect: permission denied
+ docker_id=
+ echo Docker image ID:
Docker image ID:
+ docker_inspect_cmd='docker image inspect -f "{{.RepoDigests}}" registry.gitlab.com/daviddaish/freecad_docker_env'
++ docker image inspect -f '"{{.RepoDigests}}"' registry.gitlab.com/daviddaish/freecad_docker_env
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.40/images/registry.gitlab.com/daviddaish/freecad_docker_env/json: dial unix /var/run/docker.sock: connect: permission denied
+ docker_digest=
+ echo Docker image digest:
Docker image digest:
+ [[ x = x*\e\e\7\e\3\e\c\e\e\4\c\a* ]]
+ res=0
+ docker_image=registry.gitlab.com/daviddaish/freecad_docker_env@sha256:6537079d971a332ba198967ede01748bb87c3a6618564cd2b11f8edcb42a80d0
+ echo 'Will try to pull docker image registry.gitlab.com/daviddaish/freecad_docker_env@sha256:6537079d971a332ba198967ede01748bb87c3a6618564cd2b11f8edcb42a80d0'
Will try to pull docker image registry.gitlab.com/daviddaish/freecad_docker_env@sha256:6537079d971a332ba198967ede01748bb87c3a6618564cd2b11f8edcb42a80d0
+ docker pull registry.gitlab.com/daviddaish/freecad_docker_env@sha256:6537079d971a332ba198967ede01748bb87c3a6618564cd2b11f8edcb42a80d0
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/images/create?fromImage=registry.gitlab.com%2Fdaviddaish%2Ffreecad_docker_env&tag=sha256%3A6537079d971a332ba198967ede01748bb87c3a6618564cd2b11f8edcb42a80d0: dial unix /var/run/docker.sock: connect: permission denied
+ echo 'Docker image pull failed'
Docker image pull failed
+ res=1
+ return 0
+ setup_docker_launch
+ res=0
+ for dockerscript in docker.sh docker_dev.sh docker_dev_compile.sh
+ cat /home/ofir/Downloads/Hermes//Hermes_git/freecad_build_files/docker.sh
+ sed s/:latest/@sha256:6537079d971a332ba198967ede01748bb87c3a6618564cd2b11f8edcb42a80d0/1
+ '[' '!' 0 -eq 0 ']'
+ chmod +x /home/ofir/Downloads/Hermes//docker.sh
+ '[' '!' 0 -eq 0 ']'
+ echo 'Docker launch script "docker.sh" generation'
Docker launch script "docker.sh" generation
+ for dockerscript in docker.sh docker_dev.sh docker_dev_compile.sh
+ cat /home/ofir/Downloads/Hermes//Hermes_git/freecad_build_files/docker_dev.sh
+ sed s/:latest/@sha256:6537079d971a332ba198967ede01748bb87c3a6618564cd2b11f8edcb42a80d0/1
+ '[' '!' 0 -eq 0 ']'
+ chmod +x /home/ofir/Downloads/Hermes//docker_dev.sh
+ '[' '!' 0 -eq 0 ']'
+ echo 'Docker launch script "docker_dev.sh" generation'
Docker launch script "docker_dev.sh" generation
+ for dockerscript in docker.sh docker_dev.sh docker_dev_compile.sh
+ cat /home/ofir/Downloads/Hermes//Hermes_git/freecad_build_files/docker_dev_compile.sh
+ sed s/:latest/@sha256:6537079d971a332ba198967ede01748bb87c3a6618564cd2b11f8edcb42a80d0/1
+ '[' '!' 0 -eq 0 ']'
+ chmod +x /home/ofir/Downloads/Hermes//docker_dev_compile.sh
+ '[' '!' 0 -eq 0 ']'
+ echo 'Docker launch script "docker_dev_compile.sh" generation'
Docker launch script "docker_dev_compile.sh" generation
+ return 0
+ setup_source
+ '[' '!' -d /home/ofir/Downloads/Hermes//source/.git ']'
+ git clone https://github.com/FreeCAD/FreeCAD.git /home/ofir/Downloads/Hermes//source
Cloning into '/home/ofir/Downloads/Hermes//source'...
remote: Enumerating objects: 229200, done.
remote: Total 229200 (delta 0), reused 0 (delta 0), pack-reused 229200
Receiving objects: 100% (229200/229200), 1019.07 MiB | 995.00 KiB/s, done.
Resolving deltas: 100% (192370/192370), done.
Checking connectivity... done.
Checking out files: 100% (10299/10299), done.
++ cd /home/ofir/Downloads/Hermes//source
++ git describe --tags --long
+ fchash=0.19_pre-2564-g3b97299
+ '[' x0.19_pre-2564-g3b97299 = x0.18-1194-g5a352ea63 ']'
+ cd /home/ofir/Downloads/Hermes//source
+ git reset --hard 0.18-1194-g5a352ea63
HEAD is now at 5a352ea FEM: solver fenics, fix fenics import test
++ cd /home/ofir/Downloads/Hermes//source
++ git describe --tags --long
+ fchash=0.18-1194-g5a352ea
+ '[' x0.18-1194-g5a352ea '!=' x0.18-1194-g5a352ea63 ']'
+ echo 'Hash  0.18-1194-g5a352ea63 wasn'\''t cheked out'
Hash  0.18-1194-g5a352ea63 wasn't cheked out
+ return 1
+ myexit
+ echo 'Encountered an error, leaving "/home/ofir/Downloads/Hermes"'
Encountered an error, leaving "/home/ofir/Downloads/Hermes"

**Comment by OfirBlumer** [comment]
After renaming: 

+ getopts o:b:d:f:p:i:vh opt
++ uname -s
+ OS=Linux
+ DESTINATION_FULL=
+ DOCKER_DEV=
+ DOCKER=
++ get_abs_filename ''
++++ dirname ''
+++ cd .
+++ pwd
+++ basename ''
++ echo /home/ofir/Downloads/Hermes/
+ DESTINATION_FULL=/home/ofir/Downloads/Hermes/
+ FREECAD_SOURCE_PATCH=/home/ofir/Downloads/Hermes//Hermes_git/freecad_5a352ea63_git.diff
+ mkdir -p /home/ofir/Downloads/Hermes/
+ cd /home/ofir/Downloads/Hermes/
+ DOCKER=/home/ofir/Downloads/Hermes//docker.sh
+ DOCKER_DEV=/home/ofir/Downloads/Hermes//docker_dev.sh
+ DOCKER_DEV_COMPILE=/home/ofir/Downloads/Hermes//docker_dev_compile.sh
+ git_pull HermesFlow/Hermes Hermes_git
+ res=0
+ branchopts=
+ '[' xmaster '!=' xmaster ']'
++ git clone https://github.com/HermesFlow/Hermes.git Hermes_git
+ git_clone_output='fatal: destination path '\''Hermes_git'\'' already exists and is not an empty directory.'
+ echo 'fatal: destination path '\''Hermes_git'\'' already exists and is not an empty directory.'
fatal: destination path 'Hermes_git' already exists and is not an empty directory.
+ [[ xfatal: destination path 'Hermes_git' already exists and is not an empty directory. = x*fatal:* ]]
+ [[ xfatal: destination path 'Hermes_git' already exists and is not an empty directory. = *\R\e\p\o\s\i\t\o\r\y\ \n\o\t\ \f\o\u\n\d* ]]
+ [[ xfatal: destination path 'Hermes_git' already exists and is not an empty directory. = x*fatal:* ]]
+ [[ xfatal: destination path 'Hermes_git' already exists and is not an empty directory. = *\a\l\r\e\a\d\y\ \e\x\i\s\t\s\ \a\n\d\ \i\s\ \n\o\t\ \a\n\ \e\m\p\t\y\ \d\i\r\e\c\t\o\r\y* ]]
+ echo 'Git tree HermesFlow/Hermes exist, trying to pull'
Git tree HermesFlow/Hermes exist, trying to pull
++ cd Hermes_git
++ git pull
+ git_clone_output='Already up-to-date.'
+ echo 'Already up-to-date.'
Already up-to-date.
+ return 0
+ check_docker
++ which docker
+ docker=/usr/bin/docker
+ '[' -z /usr/bin/docker ']'
+ return 0
+ setup_docker
+ docker_inspect_cmd='docker image inspect -f "{{.Id}}" registry.gitlab.com/daviddaish/freecad_docker_env'
++ docker image inspect -f '"{{.Id}}"' registry.gitlab.com/daviddaish/freecad_docker_env
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.40/images/registry.gitlab.com/daviddaish/freecad_docker_env/json: dial unix /var/run/docker.sock: connect: permission denied
+ docker_id=
+ echo Docker image ID:
Docker image ID:
+ docker_inspect_cmd='docker image inspect -f "{{.RepoDigests}}" registry.gitlab.com/daviddaish/freecad_docker_env'
++ docker image inspect -f '"{{.RepoDigests}}"' registry.gitlab.com/daviddaish/freecad_docker_env
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.40/images/registry.gitlab.com/daviddaish/freecad_docker_env/json: dial unix /var/run/docker.sock: connect: permission denied
+ docker_digest=
+ echo Docker image digest:
Docker image digest:
+ [[ x = x*\e\e\7\e\3\e\c\e\e\4\c\a* ]]
+ res=0
+ docker_image=registry.gitlab.com/daviddaish/freecad_docker_env@sha256:6537079d971a332ba198967ede01748bb87c3a6618564cd2b11f8edcb42a80d0
+ echo 'Will try to pull docker image registry.gitlab.com/daviddaish/freecad_docker_env@sha256:6537079d971a332ba198967ede01748bb87c3a6618564cd2b11f8edcb42a80d0'
Will try to pull docker image registry.gitlab.com/daviddaish/freecad_docker_env@sha256:6537079d971a332ba198967ede01748bb87c3a6618564cd2b11f8edcb42a80d0
+ docker pull registry.gitlab.com/daviddaish/freecad_docker_env@sha256:6537079d971a332ba198967ede01748bb87c3a6618564cd2b11f8edcb42a80d0
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/images/create?fromImage=registry.gitlab.com%2Fdaviddaish%2Ffreecad_docker_env&tag=sha256%3A6537079d971a332ba198967ede01748bb87c3a6618564cd2b11f8edcb42a80d0: dial unix /var/run/docker.sock: connect: permission denied
+ echo 'Docker image pull failed'
Docker image pull failed
+ res=1
+ return 0
+ setup_docker_launch
+ res=0
+ for dockerscript in docker.sh docker_dev.sh docker_dev_compile.sh
+ cat /home/ofir/Downloads/Hermes//Hermes_git/freecad_build_files/docker.sh
+ sed s/:latest/@sha256:6537079d971a332ba198967ede01748bb87c3a6618564cd2b11f8edcb42a80d0/1
+ '[' '!' 0 -eq 0 ']'
+ chmod +x /home/ofir/Downloads/Hermes//docker.sh
+ '[' '!' 0 -eq 0 ']'
+ echo 'Docker launch script "docker.sh" generation'
Docker launch script "docker.sh" generation
+ for dockerscript in docker.sh docker_dev.sh docker_dev_compile.sh
+ cat /home/ofir/Downloads/Hermes//Hermes_git/freecad_build_files/docker_dev.sh
+ sed s/:latest/@sha256:6537079d971a332ba198967ede01748bb87c3a6618564cd2b11f8edcb42a80d0/1
+ '[' '!' 0 -eq 0 ']'
+ chmod +x /home/ofir/Downloads/Hermes//docker_dev.sh
+ '[' '!' 0 -eq 0 ']'
+ echo 'Docker launch script "docker_dev.sh" generation'
Docker launch script "docker_dev.sh" generation
+ for dockerscript in docker.sh docker_dev.sh docker_dev_compile.sh
+ cat /home/ofir/Downloads/Hermes//Hermes_git/freecad_build_files/docker_dev_compile.sh
+ sed s/:latest/@sha256:6537079d971a332ba198967ede01748bb87c3a6618564cd2b11f8edcb42a80d0/1
+ '[' '!' 0 -eq 0 ']'
+ chmod +x /home/ofir/Downloads/Hermes//docker_dev_compile.sh
+ '[' '!' 0 -eq 0 ']'
+ echo 'Docker launch script "docker_dev_compile.sh" generation'
Docker launch script "docker_dev_compile.sh" generation
+ return 0
+ setup_source
+ '[' '!' -d /home/ofir/Downloads/Hermes//source/.git ']'
+ echo '"/home/ofir/Downloads/Hermes//source" appears to be a git tree, will try to checkout'
"/home/ofir/Downloads/Hermes//source" appears to be a git tree, will try to checkout
++ cd /home/ofir/Downloads/Hermes//source
++ git describe --tags --long
+ fchash=0.18-1194-g5a352ea
+ '[' x0.18-1194-g5a352ea = x0.18-1194-g5a352ea63 ']'
+ cd /home/ofir/Downloads/Hermes//source
+ git reset --hard 0.18-1194-g5a352ea63
HEAD is now at 5a352ea FEM: solver fenics, fix fenics import test
++ cd /home/ofir/Downloads/Hermes//source
++ git describe --tags --long
+ fchash=0.18-1194-g5a352ea
+ '[' x0.18-1194-g5a352ea '!=' x0.18-1194-g5a352ea63 ']'
+ echo 'Hash  0.18-1194-g5a352ea63 wasn'\''t cheked out'
Hash  0.18-1194-g5a352ea63 wasn't cheked out
+ return 1
+ myexit
+ echo 'Encountered an error, leaving "/home/ofir/Downloads/Hermes"'
Encountered an error, leaving "/home/ofir/Downloads/Hermes"

**Comment by jackitg** [comment]
Hi, 

The verification check of FC git hash fails. 
It operates as follows:
 fchash=`(cd "$DESTINATION_FULL/source";  git describe --tags --long 2>/dev/null)`

then $fchash is compared to the desired hash:

```
    #verify
    if [ "x$fchash" != "x$FREECAD_SOURCE_HASH" ]; then
        echo "Hash  $FREECAD_SOURCE_HASH wasn't cheked out"
        return 1
    fi
```
default value FREECAD_SOURCE_HASH="0.18-1194-g5a352ea63"

When inside destination/source, running the followinf cmd here : 
```
git describe --tags --long
```
produces:
0.18-1194-g5a352ea63

Please check what do you get, according to the script's debug output it is "0.18-1194-g5a352ea" (without the trailing "63"), if so, please compare the versions of "git" executables on the workstation where it works this workstation.

**Comment by jackitg** [comment]
Any news? (bump)
