### ISSUE TITLE
Permissions problems during installation

### ISSUE THREAD

**Issue by gadieid** [KaplanOpenSource/Hermes#20]
During installation, some directory are created with setuid bit flag and without write permissions so this error appears

Copying /home/davidg/Development/HermesFlow/Hermes_git/freecad_source_hermes/src to /home/davidg/Development/HermesFlow/source
Removing /home/davidg/Development/HermesFlow/build/data/Mod/Hermes
docker: Error response from daemon: error while creating mount source path '/home/davidg/Development/HermesFlow/projects': chown /home/davidg/Development/HermesFlow/projects: operation not permitted.

Also the direcrory of the build which is mounted as /mnt/build lacks write permission, and the compilations fails within the docker
root@8f3072a4d47b:/mnt/source# ./build_script.sh 
++ nproc
+ cmake -j12 -D BOOST_ROOT=/usr/local/include/boost -D BUILD_QT5=ON -D BUILD_FEM=ON -D BUILD_SANDBOX=ON -D PYTHON_LIBRARY=/usr/local/lib/libpython3.7m.so -D PYTHON_INCLUDE_DIR=/usr/local/include/python3.7 -D PYTHON_PACKAGES_PATH=/usr/local/lib/python3.7/site-packages -D PYTHON_EXECUTABLE=/usr/local/bin/python3 -D SHIBOKEN_INCLUDE_DIR=/usr/local/lib/python3.7/site-packages/shiboken2_generator/include -D SHIBOKEN_LIBRARY=/usr/local/lib/python3.7/site-packages/shiboken2/libshiboken2.cpython-37m-x86_64-linux-gnu.so.5 -D PYSIDE_INCLUDE_DIR=/usr/local/lib/python3.7/site-packages/PySide2/include -D PYSIDE_LIBRARY=/usr/local/lib/python3.7/site-packages/PySide2/libpyside2.cpython-37m-x86_64-linux-gnu.so.5 -D PYSIDE2RCCBINARY=/usr/local/lib/python3.7/site-packages/PySide2/pyside2-rcc -D 'FREECAD_USE_QTWEBMODULE=Qt\ Webkit' -S /mnt/source -B /mnt/build
CMake Error at /usr/local/share/cmake-3.16/Modules/CMakeDetermineSystem.cmake:173 (file):
  file failed to open for writing (No such file or directory):

    /mnt/build/CMakeFiles/CMakeOutput.log
Call Stack (most recent call first):
  CMakeLists.txt:25 (project)

CMake Error: Could not open file for write in copy operation /mnt/build/CMakeFiles/3.16.3/CMakeSystem.cmake.tmp
CMake Error: : System Error: No such file or directory
CMake Error at /usr/local/share/cmake-3.16/Modules/CMakeDetermineSystem.cmake:185 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:25 (project)

And so on

changing permissions solve the issue

**Comment by jackitg** [comment]
Hello, 

1.  The files in the repository have no setuid bits set, and nothing in install.sh script performs such an action, can  you please verify in a clean tree?
2.  same applies to build dir

Was the whole process performed on the same machine and  by same user?
