### ISSUE TITLE
Geometry node link Item 

### ISSUE THREAD

**Issue by yehudarav** [KaplanOpenSource/Hermes#31]
The geometry node is defined in #30 under the snappy node. 

One of its properties will be the linked item. 
double click on the node will open a web gui to define refinment and mesh specifications 
that are specific for this geomtery.

**Comment by NogaObs** [comment]
double click on geometry open a dialog box to choose part from FreeCAD
closing the dialog box create the webGui node for the part choosen, and link the part to it.

to allow the dialogBox open, a file need to be copy -
source: /Hermes_git/freecad_Resources/ui/snappygeometry.ui
destination: ../build/data/Mod/Hermes/Resources/ui/

**Comment by NogaObs** [comment]
The link item is defined through the name of the geometry,  due to limitation of property type "Link"

**Comment by yehudarav** [comment]
Ok
