### ISSUE TITLE
Export obj file from snappy node

### ISSUE THREAD

**Issue by yehudarav** [KaplanOpenSource/Hermes#34]
Export the obj from the snappy. One obj file for each geometry.

**Comment by NogaObs** [comment]
a button to export obj file from snappy has added
it export a file to object exist in snappy
it exported to the working directory - is it ok? or need to export somewhere else? User choice?

**Comment by yehudarav** [comment]
I think it is OK to have a default of the current directory and have the
capability to ask for a different directory.

**Comment by NogaObs** [comment]
After clicking the export button a dialog is opened - allow to choose a saving dir.
the default is the current working directory.
