### ISSUE TITLE
Geometry list

### ISSUE THREAD

**Issue by yehudarav** [KaplanOpenSource/Hermes#35]
Extract the list of geometries from the snappy geomtery and blockmesh nodes. 

The names of these nodes are given in the workflow JSON file as strings.  
The list in the JSON might include nodes (and the specific property) to get the objects from. 

For example: 
["blockmesh","snappyHexMesh.geometry"] 
will get all the objects of the from the blockmesh node and the geometry of the snappyHexMesh.

**Comment by NogaObs** [comment]
the list is added under GUI in BC json:
`"GeometriesSource": ["BlockMesh","SnappyHexMesh.Geometry"],`
