### ISSUE TITLE
Create items for BC

### ISSUE THREAD

**Issue by yehudarav** [KaplanOpenSource/Hermes#37]
Create a node for each geometry and  field, with the default value 'notset' (and maching icon) 

+ [Geometry name]
|
+------[ Field 1]
+------[ Field 2]
+------[ Field 3]
      
   
Double click on the field node will open a webGUI with the definitions of the boundary conditions.

**Comment by NogaObs** [comment]
![image](https://user-images.githubusercontent.com/62690442/124106990-71c5a200-da6d-11eb-8ea1-3a10d22cb29d.png)

The fields are updated at each change in the list located in the HermesWorkflow properties

The BC nodes are updated in each creation of node in snappy/BlockMesh
At the moment, the bc-geometries are not updated directly in case of deleting items from snappy/BlockMesh, only after creation.

![image](https://user-images.githubusercontent.com/62690442/124107718-31b2ef00-da6e-11eb-9639-68018ddac33d.png)
Is there anything else to display apart from the type(and any other definition related to the type)?

Another question - do the types of BC need to be separated by fields, or just have 1 list will all BC options? (at the moment it is just 1 list)
    -> for example - the "type" list of U will be taken from U json type list
                              the "type" list of P will be taken from P json type list

**Comment by yehudarav** [comment]
At the moment, lets use one list. Maybe we will change it in the future.
