### ISSUE TITLE
Change the Icon for geometry 

### ISSUE THREAD

**Issue by yehudarav** [KaplanOpenSource/Hermes#38]
Change the icon of the geometry to green circle, yellow circle and red circle. 
according to whether the BC of all the fields is defined (i.e their value is not set). 

If all the BC in the fields are defined -green, partial definition (yellow), non defined (red).

**Comment by NogaObs** [comment]
Hi, added the update of the colours of the icons.
it still have some delay - I need to figure it why

**Comment by NogaObs** [comment]
The icon is fixed - change the color depend on the state.
