### ISSUE TITLE
Update Jinja templates

### ISSUE THREAD

**Issue by yehudarav** [KaplanOpenSource/Hermes#39]
Update the jinja templates of the 

- blockMesh 
- snappy  
     Create a file for the snappy and a file for the surfaceFeatureExtract

- boundary conditions either a dictionary file for each field or one file with  the  values of all the fields. (according to a flag)

**Comment by NogaObs** [comment]
updated the BlockMesh jinja template in case of cyclic type

**Comment by yehudarav** [comment]
Did you add a 2-way reference ? (see #29)

**Comment by NogaObs** [comment]
This is how the boundary looks after applying the jinja executer:

```
boundary
(
    wall
    {
        type wall;
        faces
        (
            (4 5 6 7)
        );
    }
    a
    {
        type cyclic;
        neighbourPatch b
        faces
        (
            (0 4 7 3)
        );
    }
    b
    {
        type cyclic;
        neighbourPatch a
        faces
        (
            (1 2 6 5)
        );
    }

);
```

**Comment by yehudarav** [comment]
Perfect, 

Just add ; at the end of neighbourPatch

**Comment by NogaObs** [comment]
still need to do snappy and boundary conditions

**Comment by yehudarav** [comment]
In the blockmesh?

**Comment by NogaObs** [comment]
I added ";" at end of neighbourPatch.
but this is also jinja for snappy and boundary conditions, this is why I reopen

**Comment by yehudarav** [comment]
Why are they the same Jinja? isn't it a completely different format?

**Comment by NogaObs** [comment]
each one has its own template that need to be updated.
it is just under the same, current, issue #39

**Comment by yehudarav** [comment]
ok
