### ISSUE TITLE
Why BlockMeshExecuter is in jinjaExecuters.py?

### ISSUE THREAD

**Issue by yehudarav** [KaplanOpenSource/Hermes#42]
Is it the remains of an old code? can I remove it?

**Comment by NogaObs** [comment]
BlockMeshExecuter is also a type of jinjaExecure. 
jinjaExecuter -> for general WebGui node
BlockMeshExecuter has a differenrt structure and vars from the webGui node, and so a different executer.
This is why it is under same file, but different classes

**Comment by yehudarav** [comment]
But blockmesh is specific for openfoam. It should be there.

**Comment by NogaObs** [comment]
The Template is at  ..../jinjaTemplates/openFOAM/simpleFOAM/BlockMesh
the BlockMeshexecuter is at the jinjaExecuter.py file.
just like any other webGui node : the template is at ..../jinjaTemplates/openFOAM/simpleFOAM/Name
The executer is jinjaExecuter in jinjaExecuter.py file
there is no openfoam executer.

it is possible to change the names to be "openFOAMjinja" or something like that, but there will still be a separation in classes,  general WebGui and BlockMesh.

**Comment by yehudarav** [comment]
Yes, when its a general jina executer it makes sense, but when it's a
specific executer it should be in a specialized location.
(something like openFOAM/meshExecuters)

I think that in the future we will move the block mesh and ect to a general
openFOAM. In order to do this for the fvScheme and ect,
we need a node that will list all the variables in the solution. So maybe
we will create a specialized node for it afterall?

Another option is to make a node called solver and place all the
controlDict, fvSchemes and ect under it
In this node we could list all the fields of the solver. The snappy node
will be linked to a solver node and that was it will know all his
variables.

In variables we have to distinguish between scalar, vector and tensor
variables.

**Comment by yehudarav** [comment]
by the way, I cant find jinjaTemplates. I have (and so do you in the version of the github) 
the blockmesh is in the geometry definer.

However, as these things are specific for openFOAM, they should be under the openFOAM. 

so maybe we should create openFOAM/general and place there all the openFOAM specific nodes. 
blockMesh.
