### ISSUE TITLE
Duplicity in executers

### ISSUE THREAD

**Issue by yehudarav** [KaplanOpenSource/Hermes#43]
Hi, 
We have a lot of duplicity in the executers. 

* pythonExecuter 
* pythonExecuters
* jijnaExecuter
* general.transformTemplateExecuter

Is it my code or your?  Can I remove things or do you use anything?

**Comment by NogaObs** [comment]
Hi,
I don't have the duplicity on my branch "noga21"
![image](https://user-images.githubusercontent.com/62690442/122354102-59c42d80-cf59-11eb-8b61-cde2c4ce2b75.png)
