### ISSUE TITLE
How do I setup the geometry for the blockmesh

### ISSUE THREAD

**Issue by yehudarav** [KaplanOpenSource/Hermes#44]
How does the connection between geometry and the JSON. 
The blockMesh executer should build the blockMesh file, right ? and so it should be linked to the 
geometry

**Comment by NogaObs** [comment]
There are 2 stages:
1. there is a class "HermesPart" in HermesPart.py file - this class take the cube(it works only for box/cube shapes) and translate the FreeCAD obj info, into a dict with organised data of faces and vertices to be used in the BlockMesh node.
2. At HemesNoda.py there is class "_BlockMeshNode", with the function "backupNodeData". This class take the dict created in (1) and push the data into the JSON of BlockMesh. 
the part data used, is the one linked to the BlockMesh node(in case there are more).

**Comment by yehudarav** [comment]
Does it work without FreeCAD gui? (only from command line, after you have
installed the freecad package)
