### ISSUE TITLE
Problems with blockMesh template

### ISSUE THREAD

**Issue by yehudarav** [KaplanOpenSource/Hermes#45]
Hi 
The blockmesh  template has Property05 and ect that are really not intuitive. 
the json for the blockmesh should be simpler. I will try to change it now.

**Comment by NogaObs** [comment]
Hi,
I can change the properties structures in 1 of 2 options:
1. list of dict items - same structure
2. replace the "PropertyNum" with the prop name.

If it is ok, I'll rather make the changes for all the things include in the GUI section at the JSON. it has its impact both in JSON structures of other nodes, and the code method to read the data - so I'll make the updates in all places

let me know what option you like more, or any other option you think is better, and I'll make the changes

**Comment by yehudarav** [comment]
Please see the main and the issues that describe how I changed the
structure of the code.
