### ISSUE TITLE
New structure of blockMesh and snappyHexMesh

### ISSUE THREAD

**Issue by yehudarav** [KaplanOpenSource/Hermes#46]
Commit db8aec4 (on yehudaa branch) consists of a new structure for the blockMesh and the snappyHexMesh. 

The essence of the change is this: 

The JSON file of the the node consists all the parameters for the jinja template of either blockMesh or snappyHex mesh in the input_parameters. 

For example the blockMesh json is: 
```json
"blockMesh": {
        "Template": "openFOAM.general.BlockMesh.BlockMeshTemplate",
        "Execution": {
          "input_parameters": {
            "geometry": {
              "convertToMeters": "1",
              "cellCount": [25,20,20],
              "grading": [1,1,1]
            },
            "boundary": [
              {
                "name": "inlet",
                "type": "patch",
                "faces": [
                  [0,3,7,4]
                ]
              },
              {
                "name": "outlet",
                "type": "patch",
                "faces": [
                  [1,5,6,2]
                ]
              },
              {
                "name": "ground",
                "type": "wall",
                "faces": [
                  [0,1,2,3]
                ]
              },
              {
                "name": "frontAndBack",
                "type": "symmetry",
                "faces": [
                  [0,4,5,1],
                  [3,2,6,7],
                  [4,7,6,5]
                ]
              }
            ],
            "vertices": [
              [-20,-50,0],
              [330,-50,0],
              [330,230,0],
              [-20,230,0],
              [-20,-50,140],
              [330,-50,140],
              [330,230,140],
              [-20,230,140]
            ]
          }
        }
      }
```

This JSON is natural for the blockMesh jinja template (that was simplified greately). 

Now, this JSON is not compatible with the JSON of the webGUI. Matching the two (actually converting the webGUI json to the blockMesh JSON should occur in the 'run' method of the blockMesh executer (that inherits from jimja). 

So now we need to build the code that checks if the input JSON is from a webGUI or the native blockMesh.  If it is from webGUI then the code should convert it to the right format and pass to the jinja engine.

**Comment by NogaObs** [comment]
Hi, question about the snappy structures:
This is from the Json you sent me for 1 object:

`"buildings": {
                  "objectName": "buildings",
                  "objectType": "obj",
                  "levels": "1",
                  "ObjectRegions": {
                  },
                  "refinementSurfaceLevels": [3,3],
                  "patchType" : "wall"
                }`

          
 This is the current json formData exist in the webGui:

 `"formData": {
                                            "typeTSM": "triSurfaceMesh",
                                            "featuresTSM": {
                                                "file": "jhg",
                                                "levels": "23"
                                            },
                                            "refinementSurfacesTSM": {
                                                "patchInfo": {
                                                    "type": "ghg"
                                                },
                                                "level": "234"
                                            },
                                            "layersTSM": {
                                                "nSurfaceLayers": 35
                                            },
                                            "scaleTSM": 43,
                                            "nameTSM": "hjgh"
                                        }`


I get a little trouble to merge them cause of more/less information and some repeat words like "level".
I can adjust the webGui json or  the inputParamaters json or both, so the transfer will be easier.
what do you think?

**Comment by yehudarav** [comment]
Here is the current updated snappy hex mesh.

Note that objectRegion was changed to refinementRegion.

  "input_parameters": {
    "geometry": {
      "objects": {
        "station": {
          "objectName": "station",
          "objectType": "obj",
          "levels": "1",
          "refinementRegions": {
            "mode": "distance",
            "levels": [
              [
                0.1,
                3
              ],
              [
                0.2,
                2
              ],
              [
                0.5,
                1
              ]
            ]
          },
          "refinementSurfaceLevels": [
            1,
            1
          ],
          "patchType": "wall",
          "regions": {
            "Walls": {
              "name": "Walls",
              "type": "wall"
            },
            "PlatformSupplyAir": {
              "name": "PlatformSupplyAir",
              "type": "patch"
            },
            "PlatformReturnAir": {
              "name": "PlatformReturnAir",
              "type": "patch"
            },
            "ConcourseReturnAir": {
              "name": "ConcourseReturnAir",
              "type": "patch"
            },
            "ConcourseSupplyAir": {
              "name": "ConcourseSupplyAir",
              "type": "patch"
            },
            "ConcourseSupplyAirTop": {
              "name": "ConcourseSupplyAirTop",
              "type": "patch"
            },
            "Stairs1": {
              "name": "Stairs1",
              "type": "wall"
            },
            "Stairs2": {
              "name": "Stairs2",
              "type": "wall"
            },
            "Stairs3": {
              "name": "Stairs3",
              "type": "wall"
            },
            "Entrance1Opening": {
              "name": "Entrance1Opening",
              "type": "patch"
            },
            "Entrance2Opening": {
              "name": "Entrance2Opening",
              "type": "patch"
            },
            "Entrance3Opening": {
              "name": "Entrance3Opening",
              "type": "patch"
            }
          }
        }
      }
    },
    "castellatedMeshControls": {
      "nCellsBetweenLevels": 8,
      "minRefinementCells": 40,
      "locationInMesh": [
        0,
        -5,
        17
      ]
    }
  }
}

I think we should change the webGUI to be more oriented to the structure of
the current input_parameters.

This is because the current input_parameters JSON is more 'object oriented'
in the sense that it includes all the data that
is necessary for an object.

Therefore, it is more logical that the GUI will unite all the data you have
to specify on an object.

So when you add a new object you have to specify:

1. name ( this is the key of the object).
2. the object and its regions.
3. the refinementRegions (see the manual for the options. it is inside,
outside and distance)
3. the refinementSurfaceLevels ( a list).

So this whole section 'duplicates' when you add a new object to the GUI.

**Comment by NogaObs** [comment]
I want to make sure the snappy WebGui structure - from user perspective:
This an object in your json:
`"station":{
               "objectName":"station",
               "objectType":"obj",
               "levels":"1",
               "refinementRegions":{
                  "mode":"distance",
                  "levels":[
                     [0.1,3],
                     [0.2,2],
                     [0.5,1]
                  ]
               },
               "refinementSurfaceLevels":[1,1],
               "patchType":"wall",
               "regions":{`

_**each geometry object should have(?) -**_
**objectName** - very straightforward
**objectType** - is it always "obj"? can it be anything else?
**levels** - should be a list or 1 argument or list of lists? [jsonReact - Arrays?](https://rjsf-team.github.io/react-jsonschema-form/)
**refinementRegions** - 
     should include both "mode" and "levels", anything else?
     mode values should be [inside, outdise, distance, ..], or free test?
     levels - same question as before as before
**refinementSurfaceLevels** - list
**patchType** - can only be wall or patch, right?
**regions** - list of objects to apply the refinment? are they deffined in FreeCAD, or sort of searchable object
               each region have only 2  definition - type and name, may need more definition?
               
I'm also going through [snappyHexMesh slides](http://www.wolfdynamics.com/wiki/meshing_OF_SHM.pdf) to understand the process

**Comment by yehudarav** [comment]
*objectType - *could be stl or obj.
*levels* : 1 float
*refinementRegions: *(see
https://cfd.direct/openfoam/user-guide/v6-snappyhexmesh/)
*    -  *only mode and levels.
    - mode is inside, outside and distance.

    - if inside/outside then in the  levels
               The user enters a number xx  -> ((1.0 XX)).  ## the 1.0 is
ignored)
      if distance
               The user enters a list of 2 numbers:  distance and
refinement level. --> ( (0.2 3) (1 2) )

*refinementSurfaceLevels - *the user enter 2 numbers: refinement on the X
and on the Y dimensions.
*patchType* - yes,  I think so.
*regions - *No, these are the regions in the STL/OBJ. The searchable
regions you are referring to
               will be defined in a different key at the same level of the
geometry:
               geometry : { station : { } },
               regions : { ...}

**Comment by NogaObs** [comment]
Hi,
I think about separate the long snappyHexMesh webGui to different nodes.
At the moment it looks like this:
![image](https://user-images.githubusercontent.com/62690442/130946594-b2cca355-bd4f-4691-8bee-046ebfa01b24.png)

I would like to add a node to castellatedMeshControls, snapControls, addLayersControls and meshQualityControls under the snappyHemMesh main node. Each one will have its own webgui. 
doubleclick on the parent node will contain only of the "modules" (as it is in the updated json)

is it ok?

**Comment by NogaObs** [comment]
Hi,
The current structure in FreeCAD -  for BlockMesh, snappyHexMesh and BoundryCondiotion is as follow:
![image](https://user-images.githubusercontent.com/62690442/131323460-c277dd9b-e9e1-4036-983a-919ebe63d046.png)

for **BlockMesh** and **snappyHexMesh** the **input_parameters** is updated like in the example you sent.

**BlockMesh**: 
1. define the partLink in properties
2. doubleClick on the BlockMesh node to create a new item: define - name, type and faces
3. doubleClick on item to edit name or faces

**snappyHexMesh**
1. Each snappyHexMesh sub node(except Geometry&Refinement) is a WebGui -> doubleClick will open a webGui form - include snappyHesMes itself which contain the modules.
2. Geometry
          - DoubleClick on Geometry will open a dialog box -> choose part from list and press Ok
          - a new Geometry entity node will be created under Geometry. it will have the name snaapy_partName. 
          - the webGui of the entity will be opened auto.
3. Refinement - do nothing at the moment

**BoundaryCondition**
1. when an object is created at BlockMesh or snappyHexMesh.Geometry (as defined in the json) a new object is created at the BoundryCondition node. The object has the name bc_objectName
2. each bc object has the field objects - as defined is the HermesWorkflow1 properties 'Calculated Fields'
3. doubleClick on bc object field will open a webGui
4. the color of the icons are as follow:
       - red:      nothing has been completed
       - yellow: some have been completed, still need to complete 
       - green:  complete 
     it it true for the field objects, the bc Objects and the BoundryCondition node itself
