### ISSUE TITLE
fvSolution - webGui

### ISSUE THREAD

**Issue by NogaObs** [KaplanOpenSource/Hermes#47]
Hi,
I want to fix the webGui structure and adjust it to the "input_parameters" structure.
It seem to have 3 parts: fields, solverProperties and relaxationFactors.
The idea is to do something similar to the BC - each field will be a node under fvSolution 
the structure will be:

```
"fieldName": {
    "solver": "",
    "preconditioner": "",
    "tolerance": ,
    "relTol": ,
    "maxIter": ,
    "final": {
    	"solver": ",
        "preconditioner": "",
        "tolerance": ,
        "relTol": ,
        "maxIter": 
    },
    "solverProperties":{
    	"residualControl":
   	},
   	"relaxationFactors":{
   		"field":
   		"equations":{
   			"factor":
   			"final":
   		}
   	}
          
}
```

and the rest of the solverProperties (solverFields properties and algorithem) will be defined at the fvSolution webGui, or in another sub node?

is it seem okay from user perspective?

**Comment by yehudarav** [comment]
What easier? Another sub node 'general' or in the node itself?

**Comment by NogaObs** [comment]
same difficulty - the important thing is that it will be intuitive for the user

**Comment by yehudarav** [comment]
So i think that the main node will be better (but i am a not a ui person)

**Comment by NogaObs** [comment]
fvSolution webGui is updated
use the following example to upload in FreeCAD:
 _simpleFOAM_GUI.simpleFOAM.json_
