### ISSUE TITLE
fvSchemes - webGui

### ISSUE THREAD

**Issue by NogaObs** [KaplanOpenSource/Hermes#48]
Hi,
Also want to fix fvSchemes webGui and adjust it to the input_parameters

THe fvSchemes webGui will contain the "default" data:
```
"default": {
    "ddtScheme": "Euler",
    "gradSchemes": {
    "type": "Gauss",
     "name": "linear"
    },
    "divSchemes": {
    	"type": "Gauss",
        "name": "linear",
        "parameters": ""
    },
    "interpolationSchemes": "linear",
    "snGradSchemes": "uncorrected",
    "wallDist": "meshWave"
}
```
Each Field will be a sub node under the fvSchemes (just like the BC node) - will contain 
```
"fieldName":{
	"fluxRequired ": true,
	"divSchemes": [],    
	"laplacianSchemes": []
}
```

when: divSchemes / laplacianSchemes items structure will be

```
divSchemes / laplacianSchemes
{
    "noOfOperators": 2,
    "coefficient": "(1|A(U))",
    "type": "Gauss",
    "name": "linear",
    "parameters": "uncorrected"
}
```
and each property will be chosen from a list.

is it seems OK?

**Comment by yehudarav** [comment]
Yeah

**Comment by NogaObs** [comment]
fvSchemes webGui is updated 
use the following example to upload in FreeCAD:
 _simpleFOAM_GUI.simpleFOAM.json_
